
import Image from "next/image";
import { ROLES, type Role } from "@/lib/characters";
import { type DraftedCharacterState } from "./room-page";
import { CaptainIcon } from "./icons/captain-icon";
import { ViceCaptainIcon } from "./icons/vice-captain-icon";
import { NavigatorIcon } from "./icons/navigator-icon";
import { SniperIcon } from "./icons/sniper-icon";
import { CookIcon } from "./icons/cook-icon";
import { DoctorIcon } from "./icons/doctor-icon";
import { ShipwrightIcon } from "./icons/shipwright-icon";
import { CombatantIcon } from "./icons/combatant-icon";
import { cn } from "@/lib/utils";

const roleIcons: Record<Role, React.ComponentType<{ className?: string }>> = {
  Captain: CaptainIcon,
  "Vice-Captain": ViceCaptainIcon,
  Navigator: NavigatorIcon,
  Sniper: SniperIcon,
  Cook: CookIcon,
  Doctor: DoctorIcon,
  Shipwright: ShipwrightIcon,
  Combatant: CombatantIcon,
};

type CrewCertificateProps = {
  crew: Record<Role, DraftedCharacterState | null>;
  score: number;
  roomId: string;
  isVisible: boolean;
};

export default function CrewCertificate({ crew, score, roomId, isVisible }: CrewCertificateProps) {
  return (
    <div
      id="crew-certificate"
      className={cn(
        "fixed left-[-9999px] top-0 p-8 font-sans",
        "w-[1200px] h-[630px] overflow-hidden",
        isVisible ? "opacity-100" : "opacity-0 -z-50"
      )}
    >
      <img src="/rating_bg.png" alt="Certificate Background" className="absolute top-0 left-0 w-full h-full object-cover -z-10" />
      <div className="relative z-10">
        <div className="flex justify-between items-start text-white">
          <div>
            <h1 className="text-5xl font-bold font-headline">My One Piece Crew</h1>
            <p className="text-xl text-yellow-300">Room Code: {roomId}</p>
          </div>
          <div className="text-right">
            <p className="text-2xl font-headline">Final Score</p>
            <p className="text-6xl font-bold font-headline text-yellow-300">{score.toFixed(1)}</p>
          </div>
        </div>

        <div className="grid grid-cols-4 gap-4 mt-8">
          {ROLES.map(role => {
            const member = crew[role];
            const Icon = roleIcons[role];
            return (
              <div key={role} className="bg-card/80 backdrop-blur-sm rounded-lg p-3 flex flex-col items-center border border-yellow-700/50 shadow-lg">
                <div className="flex items-center gap-2 text-amber-100 mb-2">
                  <Icon className="w-5 h-5" />
                  <span className="font-bold text-base">{role}</span>
                </div>
                {member ? (
                  <>
                    <div className="w-full h-40 relative mt-1 rounded overflow-hidden">
                      <Image 
                        src={member.imageUrl} 
                        alt={member.info.name} 
                        fill 
                        className="object-cover object-top" 
                        sizes="250px"
                        unoptimized
                      />
                    </div>
                    <p className="mt-2 font-bold text-lg text-center text-white truncate w-full">{member.info.name}</p>
                  </>
                ) : (
                  <div className="w-full h-40 flex items-center justify-center mt-1 bg-black/20 rounded">
                    <span className="text-muted-foreground text-2xl">?</span>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>
      <p className="absolute bottom-4 right-8 text-white/50 text-sm font-headline z-10">Generated by BeatMyCrew</p>
    </div>
  );
};
