
import Image from "next/image";
import { ROLES, type Role } from "@/lib/characters";
import { type DraftedCharacterState } from "./room-page";
import { CaptainIcon } from "./icons/captain-icon";
import { ViceCaptainIcon } from "./icons/vice-captain-icon";
import { NavigatorIcon } from "./icons/navigator-icon";
import { SniperIcon } from "./icons/sniper-icon";
import { CookIcon } from "./icons/cook-icon";
import { DoctorIcon } from "./icons/doctor-icon";
import { ShipwrightIcon } from "./icons/shipwright-icon";
import { CombatantIcon } from "./icons/combatant-icon";
import { cn } from "@/lib/utils";

const roleIcons: Record<Role, React.ComponentType<{ className?: string }>> = {
  Captain: CaptainIcon,
  "Vice-Captain": ViceCaptainIcon,
  Navigator: NavigatorIcon,
  Sniper: SniperIcon,
  Cook: CookIcon,
  Doctor: DoctorIcon,
  Shipwright: ShipwrightIcon,
  Combatant: CombatantIcon,
};

type CrewCertificateProps = {
  crew: Record<Role, (DraftedCharacterState & { dataUri?: string | null }) | null>;
  score: number;
  roomId: string;
  id: string;
  isForCapture: boolean;
};

export default function CrewCertificate({ crew, score, roomId, id, isForCapture }: CrewCertificateProps) {
  return (
    <div
      id={id}
      className={cn(
        "fixed left-[-9999px] top-0 p-8 font-sans bg-background",
        "w-[1200px] h-[630px] overflow-hidden",
        { "z-50": isForCapture, "-z-50": !isForCapture }
      )}
    >
      <div className="relative z-10 flex flex-col h-full">
        <div className="flex justify-between items-start text-foreground">
          <div>
            <h1 className="text-5xl font-bold font-headline">My One Piece Crew</h1>
            <p className="text-xl text-primary">Room Code: {roomId}</p>
          </div>
          <div className="text-right">
            <p className="text-2xl font-headline text-muted-foreground">Final Score</p>
            <p className="text-6xl font-bold font-headline text-primary">{score.toFixed(1)}</p>
          </div>
        </div>

        <div className="grid grid-cols-4 gap-6 mt-8 flex-grow">
          {ROLES.map(role => {
            const member = crew[role];
            const Icon = roleIcons[role];
            const imgSrc = (isForCapture ? member?.dataUri : member?.imageUrl) || '/bmc_logo.png';
            return (
              <div key={role} className="bg-card rounded-lg p-3 flex flex-col items-center border border-border shadow-md">
                <div className="flex items-center gap-2 text-muted-foreground mb-2">
                  <Icon className="w-5 h-5" />
                  <span className="font-bold text-base">{role}</span>
                </div>
                <div className="w-full h-40 relative mt-1 rounded-sm overflow-hidden border border-border/50">
                   {member ? (
                     <Image 
                      src={imgSrc} 
                      alt={member.info.name} 
                      fill 
                      className="object-cover object-top" 
                      sizes="250px"
                      unoptimized={isForCapture}
                    />
                   ) : (
                    <div className="w-full h-full flex items-center justify-center bg-background/50">
                      <span className="text-muted-foreground text-4xl font-bold">?</span>
                    </div>
                   )}
                </div>
                <p className="mt-2 font-bold text-lg text-center text-card-foreground truncate w-full h-6 flex items-center justify-center">
                  {member ? member.info.name : ''}
                </p>
              </div>
            );
          })}
        </div>
        
        <p className="absolute bottom-2 right-4 text-muted-foreground/50 text-sm font-headline z-10">Generated by BeatMyCrew</p>
      </div>
    </div>
  );
};
